### ISSUE TITLE
Evolutions of accessible image descriptions EPUB sample

### ISSUE THREAD

**Issue by danielweck** [eKitabu/Accessible-EPUB-Toolkit#5]
Note that in the README:
"Accessible Images Sample Book" ( http://diagramcenter.org/standards-and-practices/accessible-image-sample-book.html )
and
"Download Benetech's Accessible Image Sample Book" ( https://github.com/benetech/AccessibleImageSampleBook/ )
is correct, but there is ongoing work here:
https://github.com/benetech/Accessible-Interactives-Dev/tree/master/ExtendedDescriptions/image-descriptions-testbook
(not stable yet, but worth watching)
Partially based on:
http://kb.daisy.org/publishing/docs/html/images.html#tech

**Comment by danielweck** [comment]
CC @clapierre

**Comment by clapierre** [comment]
I am going to be working with eKitabu on this project, as I was also one of the WorldVision judges (had to abstain for their proposal) but now can work with them to improve their accessibility :)

**Comment by mutterback** [comment]
Thank you both.

@clapierre  - let's connect soon. We want to be sure we're starting with a square and level foundation using the best template, in particular. Will send you mail.

Best,
Matt
